INSERT INTO movies (title, genres) VALUES ('Toy Story (1995)', 'Adventure|Animation|Children|Comedy|Fantasy');
INSERT INTO movies (title, genres) VALUES ('Jumanji (1995)', 'Adventure|Children|Fantasy');
INSERT INTO movies (title, genres) VALUES ('Grumpier Old Men (1995)', 'Comedy|Romance');
INSERT INTO movies (title, genres) VALUES ('Waiting to Exhale (1995)', 'Comedy|Drama|Romance');
INSERT INTO movies (title, genres) VALUES ('Father of the Bride Part II (1995)', 'Comedy');
INSERT INTO movies (title, genres) VALUES ('Heat (1995)', 'Action|Crime|Thriller');
INSERT INTO movies (title, genres) VALUES ('Sabrina (1995)', 'Comedy|Romance');
INSERT INTO movies (title, genres) VALUES ('Tom and Huck (1995)', 'Adventure|Children');
INSERT INTO movies (title, genres) VALUES ('Sudden Death (1995)', 'Action');
INSERT INTO movies (title, genres) VALUES ( 'GoldenEye (1995)', 'Action|Adventure|Thriller');
INSERT INTO movies (title, genres) VALUES ('American President, The (1995)', 'Comedy|Drama|Romance');
INSERT INTO movies (title, genres) VALUES ('Dracula: Dead and Loving It (1995)', 'Comedy|Horror');
INSERT INTO movies (title, genres) VALUES ('Balto (1995)', 'Adventure|Animation|Children');
INSERT INTO movies (title, genres) VALUES ('Nixon (1995)', 'Drama');
INSERT INTO movies (title, genres) VALUES ('Cutthroat Island (1995)', 'Action|Adventure|Romance');
INSERT INTO movies (title, genres) VALUES ('Casino (1995)', 'Crime|Drama');
INSERT INTO movies (title, genres) VALUES ('Sense and Sensibility (1995)', 'Drama|Romance');
INSERT INTO movies (title, genres) VALUES ('Four Rooms (1995)', 'Comedy');
INSERT INTO movies (title, genres) VALUES ('Ace Ventura: When Nature Calls (1995)', 'Comedy');
INSERT INTO movies (title, genres) VALUES ('Money Train (1995)', 'Action|Comedy|Crime|Drama|Thriller');
INSERT INTO movies (title, genres) VALUES ('Get Shorty (1995)', 'Comedy|Crime|Thriller');
INSERT INTO movies (title, genres) VALUES ('Copycat (1995)', 'Crime|Drama|Horror|Mystery|Thriller');
INSERT INTO movies (title, genres) VALUES ('Assassins (1995)', 'Action|Crime|Thriller');
INSERT INTO movies (title, genres) VALUES ('Powder (1995)', 'Drama|Sci-Fi');
INSERT INTO movies (title, genres) VALUES ('Leaving Las Vegas (1995)', 'Drama|Romance');
INSERT INTO movies (title, genres) VALUES ('Othello (1995)', 'Drama');
INSERT INTO movies (title, genres) VALUES ('Now and Then (1995)', 'Children|Drama');
INSERT INTO movies (title, genres) VALUES ('Persuasion (1995)', 'Drama|Romance');
INSERT INTO movies (title, genres) VALUES ('City of Lost Children, The (Cité des enfants perdus, La) (1995)', 'Adventure|Drama|Fantasy|Mystery|Sci-Fi');
INSERT INTO movies (title, genres) VALUES ('Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)', 'Crime|Drama');
INSERT INTO movies (title, genres) VALUES ('Dangerous Minds (1995)', 'Drama');
INSERT INTO movies (title, genres) VALUES ('Twelve Monkeys (a.k.a. 12 Monkeys) (1995)', 'Mystery|Sci-Fi|Thriller');
INSERT INTO movies (title, genres) VALUES ('Wings of Courage (1995)', 'Adventure|Romance|IMAX');
INSERT INTO movies (title, genres) VALUES ('Babe (1995)', 'Children|Drama');
INSERT INTO movies (title, genres) VALUES ('Carrington (1995)', 'Drama|Romance');
INSERT INTO movies (title, genres) VALUES ('Dead Man Walking (1995)', 'Crime|Drama');
INSERT INTO movies (title, genres) VALUES ('Across the Sea of Time (1995)', 'Documentary|IMAX');
INSERT INTO movies (title, genres) VALUES ('It Takes Two (1995)', 'Children|Comedy');
INSERT INTO movies (title, genres) VALUES ('Clueless (1995)', 'Comedy|Romance');